# Allure Environment Properties
# Generated: 2026-06-02T10:15:43.4439674
Framework=RestAssured API Automation
Reporting=Allure
OS=Windows 11
OS Version=10.0
Java Version=21.0.10
User=Admin
Base URL=https://fakestoreapi.com
